### PR TITLE
Make use of coverage

### PR DESCRIPTION
**Pull request by abouthiroppy**
Hello:)

I added nyc.

cheers.

### CODE REVIEW

**Comment by nene** [comment]
Hi, this looks pretty useful.

Could you explain a bit further what you did:

- Something strange goes on with `npm test` command. As you see, Travis tests failed, similarly they failed on my machine when I first tried them out. Specifically the smoke tests of running the whole Lebab executable failed - we probably don't care about these test for coverage. But surprisingly after I had fiddled with them, they started to work and I'm unable to make them fail again... weird. Maybe they also start to work on successive runs in Travis?
- I searched but found no documentation about this `--coverage` option of Mocha.
- Looks like nyc generates empty `coverage/` directory. Could this be disabled?

**Comment by nene** [comment]
I tried rerunning Travis build multiple times, but no success - still fails.

**Comment by abouthiroppy** [comment]
@nene Sorry for my late reply. 
I referred to https://istanbul.js.org/docs/tutorials/mocha/.
I will investigate the cause.

> I searched but found no documentation about this --coverage option of Mocha.
yep, mocha does not have `coverage` so we use `Istanbul`.

I confirmed that  `coverage/` was generated as empty.  
I don't know this cause 😭  I will check this reason.

**Comment by abouthiroppy** [comment]
I tried running `npm run travis` at my local but it has succeeded.
Try changing the timeout time.

**Comment by nene** [comment]
Yeah, this first test is really slow when running with nyc - almost 5 seconds with Node > 5 and more than 5 seconds with Node 4. Without coverage it took about 600 ms.

I think the proper route of action is to not run these tests with code-coverage enabled. These aren't unit tests anyway.

**Comment by abouthiroppy** [comment]
I agree with you. Examine how to use `nyc` only for unit tests.

**Comment by abouthiroppy** [comment]
@nene Sorry for my late reply. I have no idea.... So I 'll close once. 
Thanks a lot 🙇

**Pull request closed without merging**
