### PR TITLE
fix: fix `let/const`'s scope handling

### LINKED ISSUE #347: `var to let/const` casue "Lexical declaration cannot appear in a single-statement context."
As stated in the title, the following case will lead to invalid code.

### Input
```js
if (true) var x = 1;
```

With rule `let` on

### Expected Output
```js
if (true) {
  let x = 1;
}
```

### Actual Output
```js
if (true) let x = 1; // Lexical declaration cannot appear in a single-statement context.
```

And this is listed in the test cases:
https://github.com/lebab/lebab/blob/8c3883be34f64c6168ede351710718d63164b621/test/transform/letTest.js#L158-L165

### PR DESCRIPTION
**Pull request by pionxzh**
fixes #347

### CODE REVIEW

**Comment by nene** [comment]
Thanks for spotting the bug and providing a fix. Overall the code looks good, but I spotted one regression. Given the following code:

```js
x = 1;
if (true) var x = 2;
```

Previously this code was left unchanged, as the code relies on variable hoisting which doesn't work with let/const. But now this code gets transformed to:

```js
x = 1;
if (true) {
  var x = 2;
}
```

Which, although it doesn't change the meaning of the code, performs an unnecessary change. This deviates from the principle of Lebab not changing the style of the code. I guess that's not intentional, but just a scenario you forgot to consider.

Also, it would be interesting to know how did you encounter this bug in the first place. I imagine you must have had some code that was incorrectly transformed, but I have hard time imagining what sort of code it could have been. Because the examples you have given, don't really make much sense. Having something like:

```js
if (true) { const x = 1; }
```

is effectively dead code and having the variable doesn't make much sense. Like maybe it would be better to just leave the code untransformed and let Lebab produce a warning about an unused variable or something. Not sure. Just thinking out loud...

**Comment by pionxzh** [comment]
Thanks for your insightful feedback. 

To shed some light on the background of this issue, I'm currently developing a [Javascript decompiler / unminifier](https://github.com/unminify-kit/core) and am utilizing `lebab`'s rules to provide advanced code transformations. During the testing phase with a React application, I encountered error messages triggered by specific code snippets in React's `scheduler.production.min.js`, as seen in the example below:

```js
function z(e, n) {
  (L = !1), I && ((I = !1), i()), (A = !0);
  var r = M;
  try {
    for (
      D(n), N = O(_);
      null !== N && (!(N.expirationTime > n) || (e && !a()));

    ) {
      var u = N.callback;
      if (null !== u) {
        (N.callback = null), (M = N.priorityLevel);
        var l = u(N.expirationTime <= n);
        (n = exports.unstable_now()),
          "function" == typeof l ? (N.callback = l) : N === O(_) && C(_),
          D(n);
      } else C(_);
      N = O(_);
    }
    if (null !== N) var c = !0;
    else {
      var s = O(j);
      null !== s && o(F, s.startTime - n), (c = !1);
    }
    return c;
  } finally {
    (N = null), (M = r), (A = !1);
  }
}
```
In particular, the line if (null !== N) var c = !0; was a source of concern.

---

For the best approach to address this, I have realized that transforming
```js
x = 1;
if (true) var x = 2;
```
to
```js
x = 1;
if (true) {
  let x = 2;
}
```
does indeed introduce a behavioral change. In the initial version, x was hoisted to the global or function scope, whereas in the transformed code, the scope of x is confined to the block. This change in scope can potentially alter the behavior of the program, which is something we want to avoid.

Considering this, I believe leaving such cases untransformed would be the safest way to prevent unexpected behavior changes.

**Comment by nene** [comment]
Aha... looks like there's a currently a bug in Lebab. It really shouldn't transform the `var` in here:

```js
    if (null !== N) var c = !0;
    else {
      var s = O(j);
      null !== s && o(F, s.startTime - n), (c = !1);
    }
    return c;
```

I think the problem is indeed in how these if-statement bodies are treated. When I implemented this, I thought that the following if-statement would be valid:

```js
if (null !== N) let c = !0;
```

That because there is no block, `c` would be scoped to the surrounding function body. But it didn't even occur to me to check whether this is a valid syntax at all (after all, `var` is perfectly valid in there).

So yeah, I agree that the solution here is to leave such cases untransformed.

**Comment by pionxzh** [comment]
I have updated the code skip transformation under certain situations. I also extended the checking to cover the `while` and `do while` loop.  The perfect solution might be to combine the checking with accurate scope analysis, but I don't have enough knowledge to modify that part. But that strategy might against the principle of not changing the code style. So yeah :)

**Comment by nene** [comment]
Thanks.

I made some changes on top of yours, like generating a warning whenever a `var` is left untransformed, and merged this in.

**Comment by nene** [comment]
Published the fix in Lebab 3.2.3.

**Pull request merged**
