### PR TITLE
Bump Recast to fix binding of arrow functions

### LINKED ISSUE #105: Fails on pure functions that are spuriously bound
Consider this code:
`
var x = function() {
  return 2;
}.bind(this);
`
This incorrectly becomes `const x = () => 2.bind(this);`.

### PR DESCRIPTION
**Pull request by mdebbar**
Fixes #105 

Need to wait until https://github.com/benjamn/recast/pull/349 is merged and a new version of Recast is released.

### CODE REVIEW

**Comment by shajith** [comment]
@mdebbar, @nene: This might be unblocked now?

**Comment by mdebbar** [comment]
@shajith yes I rebased this PR today and updated it with the correct version of recast. Tests are passing and it should be good to go!

**Comment by nene** [comment]
Thanks a lot! Works nicely.

**Comment by shajith** [comment]
Awesome, thank you @mdebbar and @nene! 

Looking forward to a release with this.

**Comment by nene** [comment]
@shajith Released now in Lebab 2.7.1

**Pull request merged**
