### PR TITLE
Add code coverage using NYC and integrate with codecov

### LINKED ISSUE #212: Add code coverage using NYC and integrate with codecov
- [x] Add code coverage metrics for `lebab`
- [x] Integrate with `codecov` to push code coverage data to codecov

#### Example:

screen shot 2017-01-19 at 9 33 39 am

Sample Reference: https://github.com/addi90/build-notification-api/blob/master/package.json#L9

### PR DESCRIPTION
**Pull request by addi90**
- Closes #212 
- Add code coverage using NYC
- Separate out system tests from the unit test
- Add scripts:
    - `npm run cover`: To check coverage locally
    - `npm run system-test`: To run system test
    - `npm run check-coverage`: To check and ensure that coverage is above 80%
    - `npm run report-coverage`: To create `.lcov` based code coverage report 
    - `npm run codecov`: To upload code coverage report to **codecov**
- Update `.travis.yml` to add the scripts to be executed at right build life-cycle events

### CODE REVIEW

**Comment by addi90** [comment]
@nene @abouthiroppi Guys the code coverage report is available here: https://codecov.io/gh/lebab/lebab. If you add codecov app to list of authroised applications for this repo, we will start getting comments for successful/failed builds from codecov bot.

**Comment by nene** [comment]
This looks great. I'll take another look at this later today.

I think I'll need to fiddle a bit with dependencies between NPM scripts. Like the `test` script doesn't actually need the `prepublish` script, only the `system-test` does, but we should run `prepublish` whenever `system-test` is run.

It's also unclear to me that `codecov` task actually performs an upload. I think we need a better name to communicate it's intent.

**Comment by addi90** [comment]
Cool. Add your review comments and I will fix them based on your suggestions. I generally go with `codecov` because that makes it clear that the script is related to codecov. But any better suggestions can be applied as well

**Comment by nene** [comment]
My perspective is that I've never heard/used this codecov site before. So
to me codecov sounds just like another abbreviation of code coverage, which
looks confusingly similar to the 'cover' script.

20.01.2017 11:13 kirjutas kuupäeval "Aditya Pratap Singh" <
notifications@github.com>:

Cool. Add your review comments and I will fix them based on your
suggestions. I generally go with codecov because that makes it clear that
the script is related to codecov. But any better suggestions can be applied
as well

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lebab/lebab/pull/213#issuecomment-274018443>, or mute
the thread

**Comment by addi90** [comment]
@nene Based on your comments, I think the below would make sense even for someone who hasn't used `codecov`. Let me know what do you think?

- `cover` -> `check-coverage-dev`
-  `check-coverage` -> `ensure-coverage`
- `codecov` -> `upload-coverage`

**Comment by nene** [comment]
Tweaked it quite a bit. Performed some renames and reorganization of package.json scripts. All merged now, with coverage reports nicely running :)

Thanks once more!

**Comment by addi90** [comment]
Thanks a lot for taking care of the naming suggestions

**Pull request merged**
